name: 'Shifter Action'
description: 'Github Action to replace strings in files or directories'
inputs:
  patterns:  
    description: 'Patterns to replace'
    required: true
    default: ""
runs:
  using: 'node20'
  main: 'index.js'